- name: Install dependencies
  run: npm install

- name: Generate Prisma client
  run: npx prisma generate

- name: Run migrations
  run: npx prisma migrate deploy

- name: Seed database
  run: npx prisma db seed

- name: Run top-workplaces script
  run: npm run start:topWorkplaces

- name: Run top-workers script
  run: npm run start:topWorkers
